name: home-server

services: 
  vault-secrets:
    image: hashicorp/vault:1.18
    container_name: vault-secrets
    restart: unless-stopped
    ports:
      - "${VAULT_PORT_HOST:-8200}:8200"
    environment:
      # Définir l'adresse d'écoute de Vault
      VAULT_ADDR: http://0.0.0.0:8200
      
      # Définir le token racine principal à partir des variables d'environnement
      VAULT_DEV_ROOT_TOKEN_ID: "${VAULT_ROOT_TOKEN:-root-token}"