name: home-server

services: 
  vault-secrets:
    image: hashicorp/vault:1.18
    container_name: vault-secrets
    restart: unless-stopped
    ports:
      - "${VAULT_PORT_HOST:-8200}:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    command: "server"
    cap_add:
      - IPC_LOCK
    volumes:
      - "${VAULT_VOLUME_FILE-./data/vault/file}:/vault/file"
      - "./vault-config.json:/vault/config/vault-config.json"
